#pragma once

//Build configuration

//This file is generated by CMAKE.
//Please do not use the .template.hpp one in your code,
//and please do not modify by hand the .hpp one,
//instead change cmake options and generate again!

// clang-format off
#define USING_OPENVR @CPP_HAS_OPENVR@
#define USING_OCULUS_VR @CPP_HAS_OCULUS_VR@
#define USING_OPENXR @CPP_HAS_OPENXR@
#define USING_TILT_FIVE @CPP_HAS_TILT_FIVE@
#define GAME_NAME "@GAME_NAME@"
// clang-format on
